config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :spree do
    namespace :spree_slider_theme do
      resources :theme_colors
      resources :infos
    end
  end

  scope :module => 'spree_slider_theme' do
    resources :infos
    match "order_information" => "infos#order_information", :via => :get, :as => "order_information"
    match "search_order" => "infos#search_order", :via => :post, :as => "search_order"
  end

  namespace :admin do
    namespace :spree_slider_theme do
      resources :theme_images
      resources :infos
    end
  end

  namespace :spree_slider_theme do
    resources :theme_images
  end

  namespace :admin do
    namespace :spree do
      namespace :spree_slider_theme do
       resources :theme_colors
      end
    end
  end

  namespace :admin, :scope => "spree_slider_theme/theme_images" do
    match "enabled_selected" => "spree_slider_theme/theme_images#enabled_selected", :via => :post, :as => "enabled_selected"
    match "redirect_enabled_selected" => "spree_slider_theme/theme_images#redirect_enabled_selected", :via => :get, :as => "redirect_enabled"
  end

  namespace :admin, :scope => "spree_slider_theme/theme_colors" do
    match "edit_theme" => "spree_slider_theme/theme_colors#edit_theme", :via => :get, :as => "edit_theme"
    match "update_theme" => "spree_slider_theme/theme_colors#update_theme", :via => :post, :as => "update_theme"
  end

  # Route for newest_product, best_product
  get '/best_seller/' => 'products#best_product'
  get '/new/' => 'products#newest_product'
  get '/promo/' => 'products#promotion_product'

  match "locale/change" => "locale#change_locale", :as => "change_locale"
end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/spree_slider_theme.rb
module Spree::SpreeSliderTheme
  def self.table_name_prefix
    'spree_spree_slider_theme_'
  end
end

app/models/spree/spree_slider_theme/info.rb
class Spree::SpreeSliderTheme::Info < ActiveRecord::Base
  self.table_name = 'spree_spree_slider_theme_infos'
  attr_accessible :body, :title
end

app/models/spree/spree_slider_theme/theme_color.rb
module Spree
  module SpreeSliderTheme
    class ThemeColor < ActiveRecord::Base
      self.table_name = 'spree_spree_slider_theme_theme_colors'
      attr_accessible :color, :filename, :used
    end
  end
end

app/models/spree/spree_slider_theme/theme_image.rb
module Spree
  module SpreeSliderTheme
    class ThemeImage < ActiveRecord::Base
      self.table_name = 'spree_slider_theme_theme_images'
      attr_accessible :image, :enabled, :url_destination, :description

      has_attached_file :image, :styles => { :small => "200x200>", :thumb => "100x100>" }
      # validate :file_dimensions, :unless => "errors.any?", :on => :create

      def file_dimensions
        dimensions = Paperclip::Geometry.from_file(image.queued_for_write[:original].path)
        # width  : 1024px
        # height : 510px
        if dimensions.width < 974 || dimensions.width > 1700
          errors.add(:file, (I18n.t "messages.theme_images.range_width", :range_1 => "974", :range_2 => "1700"))
        end

        if dimensions.height < 460 || dimensions.height > 1100
          errors.add(:file, (I18n.t "messages.theme_images.range_height", :range_1 => "460", :range_2 => "510"))
        end
      end
    end
  end
end

app/controllers/spree/admin/spree_slider_theme/infos_controller.rb
class Spree::Admin::SpreeSliderTheme::InfosController < Spree::Admin::BaseController
  def index
    @infos = Spree::SpreeSliderTheme::Info.all
  end

  def edit
    @info = Spree::SpreeSliderTheme::Info.find(params[:id])
  end

  def update
    @info = Spree::SpreeSliderTheme::Info.find(params[:id])
    if @info.update_attributes(params[:spree_slider_theme_info])
      redirect_to admin_spree_slider_theme_infos_path, :notice => "#{t("fat_footer.#{@info.title}")} #{t(:updated)}"
    else
      render action: "edit", :error => @info.errors
    end
  end
end

app/controllers/spree/admin/spree_slider_theme/theme_colors_controller.rb
module Spree
  module Admin
    class SpreeSliderTheme::ThemeColorsController < ApplicationController
      include Spree::Admin::SpreeSliderTheme::ThemeColorsHelper

      def update_theme
        @old_theme = Spree::SpreeSliderTheme::ThemeColor.where(:used => "true").first
        @new_theme = Spree::SpreeSliderTheme::ThemeColor.find(params[:theme_color])
        @new_theme.used = "true"

        unless @old_theme.nil?
          @old_theme.used = "false"
          if @old_theme.save && @new_theme.save
            change_color(@old_theme, @new_theme)
            redirect_to spree.admin_spree_slider_theme_theme_images_path, :notice => (I18n.t "messages.succeed")
          else
            redirect_to spree.admin_spree_slider_theme_theme_images_path, :notice => (I18n.t "messages.failed")
          end
        else
          if @new_theme.save
            change_color(@old_theme, @new_theme)
            redirect_to spree.admin_spree_slider_theme_theme_images_path, :notice => (I18n.t "messages.succeed")
          else
            redirect_to spree.admin_spree_slider_theme_theme_images_path, :notice => (I18n.t "messages.failed")
          end
        end
      end
    end
  end
end

app/controllers/spree/admin/spree_slider_theme/theme_images_controller.rb
module Spree
  module Admin
    class SpreeSliderTheme::ThemeImagesController < Spree::Admin::BaseController
      def index
        @images = Spree::SpreeSliderTheme::ThemeImage.all
        @image = Spree::SpreeSliderTheme::ThemeImage.new
        @theme_color = Spree::SpreeSliderTheme::ThemeColor.where(:used => "true").first
        @theme_colors = Spree::SpreeSliderTheme::ThemeColor.find(:all, :order => "used DESC")
      end

      def new
        @image = Spree::SpreeSliderTheme::ThemeImage.new
      end

      def create
        @images = params[:spree_slider_theme_theme_image][:image]
        if @images.count > 1 # NOTE for multiple upload
          logger.debug("----------------------------------multipe upload")
          @index = 0
          @images.each do |image|
            @image = Spree::SpreeSliderTheme::ThemeImage.create(:image => params[:spree_slider_theme_theme_image][:image][@index])
            if @image.new_record?
              @error = true
            else
              @error = false
            end
            @index += 1
          end

          if @error == true
            redirect_to spree.admin_spree_slider_theme_theme_images_path, :notice => @image.errors.messages[:file].first
          else
            redirect_to spree.admin_spree_slider_theme_theme_images_path, :notice => (I18n.t "messages.theme_images.succeed_add")
          end
        else
          @image = Spree::SpreeSliderTheme::ThemeImage.create(:image => params[:spree_slider_theme_theme_image][:image][0])
          if @image.new_record?
            redirect_to spree.admin_spree_slider_theme_theme_images_path, :notice => @image.errors.messages[:file].first
          else
            redirect_to spree.admin_spree_slider_theme_theme_images_path, :notice => (I18n.t "messages.theme_images.succeed_add")
          end
        end
      end

      def edit
        @image = Spree::SpreeSliderTheme::ThemeImage.find(params[:id])
      end

      def update
        @image = Spree::SpreeSliderTheme::ThemeImage.find(params[:id])
        if @image.update_attributes(params[:spree_slider_theme_theme_image])
          redirect_to spree.admin_spree_slider_theme_theme_images_path, notice: (I18n.t "messages.theme_images.succeed_edit")
        else
          render action: "edit", :error => @image.errors
        end
      end

      def destroy
        @image = Spree::SpreeSliderTheme::ThemeImage.find(params[:id])
        if @image.destroy
          redirect_to spree.admin_spree_slider_theme_theme_images_path, :notice => (I18n.t "messages.theme_images.succeed_destroy")
        else
          redirect_to spree.admin_spree_slider_theme_theme_images_path, :notice => @image.errors
        end
      end

      def enabled_selected
        @arr_images = params[:arr_images]
        @arr_images_o = Spree::SpreeSliderTheme::ThemeImage.where(:enabled => "true")
        @arr_images_o.each do |image|
          image.enabled = "false"
          image.save
        end

        @arr_images.each do |image|
          @data = Spree::SpreeSliderTheme::ThemeImage.find(image)
          @data.enabled = "true"

          if @data.save
            @notice = "s"
          else
            @notice = "f"
          end
        end

        respond_to do |format|
          format.json { render :json => {:notice => @notice} }
        end
      end

      def redirect_enabled_selected
        if params[:notice] == "s"
          @notice = I18n.t "messages.succeed"
        else
          @notice = I18n.t "messages.failed"
        end

        redirect_to spree.admin_spree_slider_theme_theme_images_path, :notice => @notice
      end
    end
  end
end

app/controllers/spree/spree_slider_theme/infos_controller.rb
class Spree::SpreeSliderTheme::InfosController < Spree::BaseController
  helper "Spree::Products"
  include Spree::SpreeSliderTheme::InfosHelper
  before_filter :new_variable

  def new_variable
    load_new_variable
  end

  def show
    @info = Spree::SpreeSliderTheme::Info.find(params[:id])
  end

  def order_information
    @order = Spree::Order.new
  end

  def search_order
    @order = Spree::Order.find_by_number(params[:order][:number])
    @customer = "#{@order.bill_address.firstname} #{@order.bill_address.lastname}" unless @order.nil?
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/spree/admin/spree_slider_theme/theme_colors_helper.rb
module Spree::Admin::SpreeSliderTheme::ThemeColorsHelper
  def change_color(old_theme, new_theme)
    @file = File.readlines('./app/assets/stylesheets/store/all.css')
    index = 0
    find = false

    unless old_theme.nil?
      @file.each do |f|
        if f.include?(old_theme.filename)
          find = true
          break
        end
        index += 1
      end
    end
    @file.delete_at(index) if find
    index = @file.count - 2 if index == 0
    @file.insert(index, " *= require store/spree_slider_theme/#{new_theme.filename}\n")
    File.open('./app/assets/stylesheets/store/all.css', 'w+') { |f| f.write @file.join() }
  end
end

app/helpers/spree/spree_slider_theme/infos_helper.rb
module Spree::SpreeSliderTheme::InfosHelper
  def load_new_variable
    @contact_us = Spree::SpreeSliderTheme::Info.find_by_title("contact_us")
    @how_to_shop = Spree::SpreeSliderTheme::Info.find_by_title("how_to_shop")
    @confirm_transfer = Spree::SpreeSliderTheme::Info.find_by_title("confirm_transfer")
  end

  def check_locales(locale)
    find = false
    I18n.available_locales.each do |l|
      if locale.to_s == l.to_s
        find = true
        break
      end
    end
    return find
  end
end

app/helpers/spree/spree_slider_theme/theme_colors_helper.rb
module Spree::SpreeSliderTheme::ThemeColorsHelper
end

app/views/spree/layouts/_fat_footer.html.erb
<script style="text/javascript">
  $(document).ready(function(){
    $("nav#taxonomies").addClass("taxon-fat-footer");
  });
</script>

<% if !current_page?(root_path) %>
  <div style="clear:both"></div>
  <div id="fat-footer">
    <% get_taxonomies.each do |taxonomy| %>
      <div class="fat-footer-taxon">
      <h6 class='taxonomy-root'><%= taxonomy.name %></h6>
      <%= taxons_tree(taxonomy.root, @taxon, Spree::Config[:max_level_in_taxons_menu] || 1) %>
      </div>
    <% end %>
    <div class="fat-footer-taxon">
      <h6 class='taxonomy-root'><%= t :service %></h6>
      <ul class="taxons-list">
        <li>
          <% unless @contact_us.nil? %>
            <%= link_to (t "fat_footer.contact_us"), info_path(@contact_us) %>
          <% else %>
            <%= link_to (t "fat_footer.contact_us"), "#" %>
          <% end %>
        </li>
        <li>
          <% unless @how_to_shop.nil? %>
            <%= link_to (t "fat_footer.how_to_shop"), info_path(@how_to_shop) %>
          <% else %>
            <%= link_to (t "fat_footer.how_to_shop"), "#" %>
          <% end %>
        </li>
        <% if !@confirm_transfer.nil? %>
          <li><%= link_to (t "fat_footer.confirm_transfer"), info_path(@confirm_transfer) %></li>
        <% end %>
        <li><%= link_to (t "fat_footer.order_information"), order_information_path %></li>
      </ul>
    </div>
  </div>
<% end %>

app/views/spree/layouts/_home_pictures.html.erb
<div id="featured">
	<div class="image_categories">
    <% if @list_best_products.nil? || @list_best_products.empty? %>
      <%= link_to (image_tag 'store/spree_slider_theme/default/no-product.jpg', :width => 310, :height => 207), "#" %>
    <% else %>
      <% @help = @list_best_products.first %>
      <% if @help.images.first.attachment.styles.select{ |i| i == "feature"}.length == 1 %>
        <%= link_to feature_image(@help, :itemprop => "image"), @help, :itemprop => 'url' %>
      <% else %>
        <%= link_to small_image(@help, :itemprop => "image", :width => 310, :height => 207), best_seller_path, :itemprop => 'url' %>
      <% end %>
    <% end %>
		<div class="promotion">
      <div class="tag_promotion"><%= t :best_products_title %></div>
		</div>
	</div>
	
	<div class="image_categories">
    <% if @list_new_products.nil? || @list_new_products.empty? %>
      <%= link_to (image_tag 'store/spree_slider_theme/default/no-product.jpg', :width => 310, :height => 207), "#" %>
    <% else %>
      <% @help = @list_new_products.first %>
      <% if @help.images.first.attachment.styles.select{ |i| i == "feature"}.length == 1 %>
        <%= link_to feature_image(@help, :itemprop => "image"), @help, :itemprop => 'url' %>
      <% else %>
        <%= link_to small_image(@help, :itemprop => "image", :width => 310, :height => 207), new_path, :itemprop => 'url' %>
      <% end %>
    <% end %>
		<div class="promotion">
      <div class="tag_promotion"><%= t :newest_products_title %></div>
		</div>
	</div>
	
	<div class="image_categories">
    <% if @list_promotion_products.nil? || @list_promotion_products.empty? %>
      <%= link_to (image_tag 'store/spree_slider_theme/default/no-product.jpg', :width => 310, :height => 207), "#" %>
    <% else %>
      <% @help = @list_promotion_products.first %>
      <% if @help.images.first.attachment.styles.select{ |i| i == "feature"}.length == 1 %>
        <%= link_to feature_image(@help, :itemprop => "image"), @help, :itemprop => 'url' %>
      <% else %>
        <%= link_to small_image(@help, :itemprop => "image", :width => 310, :height => 207), promo_path, :itemprop => 'url' %>
      <% end %>
    <% end %>
		<div class="promotion">
      <div class="tag_promotion"><%= I18n.t :promotion_products_title %></div>
		</div>
	</div>
</div>

<div style="clear: both;"></div>

app/views/spree/layouts/_menu_theme.html.erb
<%= tab :theme_images, :url => spree.admin_spree_slider_theme_theme_images_path %>
<%= tab :infos, :url => spree.admin_spree_slider_theme_infos_path %>

app/views/spree/layouts/_slider.html.erb
<% if current_page?(root_path) %>
  <% if !@slider_images.nil? && @slider_images.count > 0 %>
    <div id='wrapper' class='slider_pict' style='margin-bottom:50px;'>
      <div class='slider-wrapper theme-default'>
        <div id='slider' class='nivoSlider' style='height:510px; width:1024px;'>
          <% @slider_images.each do |image| %>
            <% destination = image.url_destination %>
            <% if destination.nil? %>
              <% destination = "#" %>
            <% end %>
            <% if !image.description.nil? && !image.description.empty? %>
              <% title = "<a href='#{destination}'>#{image.description}</a>" %>
              <%= image_tag image.image.url(:original), :title => title %>
            <% else %>
              <%= image_tag image.image.url(:original) %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="slider_pict"></div>
  <% end %>
<% end %>